// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0pcf43X5_2B56hT0nAQ1WgKrAOptPG08',
    appId: '1:304398038365:web:bc4a8b31cb7391789e64b4',
    messagingSenderId: '304398038365',
    projectId: 'joblatter-36cbb',
    authDomain: 'joblatter-36cbb.firebaseapp.com',
    storageBucket: 'joblatter-36cbb.appspot.com',
    measurementId: 'G-T3E8T99MFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPEv8pzGKGeYQv2vhIca3E4STJh5Vj-wk',
    appId: '1:304398038365:android:2318d8029a5561b19e64b4',
    messagingSenderId: '304398038365',
    projectId: 'joblatter-36cbb',
    storageBucket: 'joblatter-36cbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb8o38j8-uoerIAkAHSJ7kNSu7ymFP4fE',
    appId: '1:304398038365:ios:997004ba4b7e41689e64b4',
    messagingSenderId: '304398038365',
    projectId: 'joblatter-36cbb',
    storageBucket: 'joblatter-36cbb.appspot.com',
    androidClientId: '304398038365-lskdqlm69vpbt0ju8oea3p91l07clk6c.apps.googleusercontent.com',
    iosClientId: '304398038365-5bd7ttifutjprvtq4s1dph4uisnuksj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobLetter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb8o38j8-uoerIAkAHSJ7kNSu7ymFP4fE',
    appId: '1:304398038365:ios:864b8b18173fa4629e64b4',
    messagingSenderId: '304398038365',
    projectId: 'joblatter-36cbb',
    storageBucket: 'joblatter-36cbb.appspot.com',
    androidClientId: '304398038365-lskdqlm69vpbt0ju8oea3p91l07clk6c.apps.googleusercontent.com',
    iosClientId: '304398038365-9mqum7o07en1peo94kibln15909pmafg.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobLetter.RunnerTests',
  );
}
